version: "3"
services:
  web:
    build: .
    env_file:
      - ./dev.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/www
    depends_on:
      - db_dev
  db_dev:
    image: "postgres:14.5-alpine"
    env_file:
      - ./dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
