version: "3"
services:
  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/static
      - ./media:/media
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    env_file:
      - ./prod.env
    command: gunicorn --bind 0.0.0.0:8080 config.wsgi
    ports:
      - "8080:8080"
    volumes:
      - .:/www
    depends_on:
      - db_prod
  db_prod:
    image: "postgres:14.5-alpine"
    env_file:
      - ./prod.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_prod:
