# Generated by Django 4.1 on 2022-11-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fido', '0004_alter_contact_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
