# Generated by Django 4.1 on 2022-11-11 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fido', '0005_delete_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('age', models.CharField(choices=[('Puppy', 'Puppy'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], default='Puppy', max_length=6)),
                ('breed', models.CharField(choices=[('Basset Hound', 'Basset Hound'), ('Beagle', 'Beagle'), ('Border Collie', 'Border Collie'), ('Boston Terrier', 'Boston Terrier'), ('Boxer', 'Boxer'), ('Cockapoo', 'Cockapoo'), ('Cocker Spaniel', 'Cocker Spaniel'), ('French Bulldog', 'French Bulldog'), ('Golden Retriever', 'Golden Retriever'), ('Greyhound', 'Greyhound'), ('Irish Setter', 'Irish Setter'), ('Labrador Retriever', 'Labrador Retriever'), ('Poodle', 'Poodle')], default='Basset Hound', max_length=18)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fido.shelter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('age', models.CharField(choices=[('Kitten', 'Kitten'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], default='Kitten', max_length=6)),
                ('breed', models.CharField(choices=[('Abyssinian', 'Abyssinian'), ('Bengal', 'Bengal'), ('Birman', 'Birman'), ('Devon Rex', 'Devon Rex'), ('Egyptian Mau', 'Egyptian Mau'), ('Foldex', 'Foldex'), ('Himalayan', 'Himalayan'), ('Maine Coon', 'Maine Coon'), ('Persian', 'Persian'), ('Ragdoll', 'Ragdoll'), ('Scottish Fold', 'Scottish Fold'), ('Siamese', 'Siamese'), ('Sphynx', 'Sphynx')], default='Abyssinian', max_length=13)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fido.shelter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
