# Generated by Django 4.1 on 2022-11-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fido', '0006_dog_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['-pk']},
        ),
    ]
