# Generated by Django 4.1 on 2022-11-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fido', '0007_alter_cat_options_alter_dog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={},
        ),
    ]
