# Generated by Django 4.1 on 2022-11-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fido', '0008_alter_cat_options_alter_dog_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
    ]
