# Generated by Django 4.1 on 2022-11-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fido', '0009_rename_contact_message'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['sex', 'shelter', 'age', 'breed'], name='fido_cat_sex_4c7286_idx'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['sex', 'shelter', 'age', 'breed'], name='fido_dog_sex_c957c4_idx'),
        ),
        migrations.AddIndex(
            model_name='shelteraddress',
            index=models.Index(fields=['state', 'shelter'], name='fido_shelte_state_8ca7e2_idx'),
        ),
    ]
