PETS_PER_PAGE = 12
APPROX_CAT_COUNT = 37500
APPROX_DOG_COUNT = 21700
SEXES = (
    ('Male', 'Male'),
    ('Female', 'Female')
)
CAT_AGE_RANGES = (
    ('Kitten', 'Kitten'),
    ('Young', 'Young'),
    ('Adult', 'Adult'),
    ('Senior', 'Senior')
)
DOG_AGE_RANGES = (
    ('Puppy', 'Puppy'),
    ('Young', 'Young'),
    ('Adult', 'Adult'),
    ('Senior', 'Senior')
)
CAT_BREEDS = (
    ('Abyssinian', 'Abyssinian'),
    ('Bengal', 'Bengal'),
    ('Birman', 'Birman'),
    ('Devon Rex', 'Devon Rex'),
    ('Egyptian Mau', 'Egyptian Mau'),
    ('Foldex', 'Foldex'),
    ('Himalayan', 'Himalayan'),
    ('Maine Coon', 'Maine Coon'),
    ('Persian', 'Persian'),
    ('Ragdoll', 'Ragdoll'),
    ('Scottish Fold', 'Scottish Fold'),
    ('Siamese', 'Siamese'),
    ('Sphynx', 'Sphynx'),
)
DOG_BREEDS = (
    ('Basset Hound', 'Basset Hound'),
    ('Beagle', 'Beagle'),
    ('Border Collie', 'Border Collie'),
    ('Boston Terrier', 'Boston Terrier'),
    ('Boxer', 'Boxer'),
    ('Cockapoo', 'Cockapoo'),
    ('Cocker Spaniel', 'Cocker Spaniel'),
    ('French Bulldog', 'French Bulldog'),
    ('Golden Retriever', 'Golden Retriever'),
    ('Greyhound', 'Greyhound'),
    ('Irish Setter', 'Irish Setter'),
    ('Labrador Retriever', 'Labrador Retriever'),
    ('Poodle', 'Poodle'),
)
US_STATES = (
    ('Alabama', 'Alabama'),
    ('Alaska', 'Alaska'),
    ('Arizona', 'Arizona'),
    ('Arkansas', 'Arkansas'),
    ('California', 'California'),
    ('Colorado', 'Colorado'),
    ('Connecticut', 'Connecticut'),
    ('Delaware', 'Delaware'),
    ('Florida', 'Florida'),
    ('Georgia', 'Georgia'),
    ('Hawaii', 'Hawaii'),
    ('Idaho', 'Idaho'),
    ('Illinois', 'Illinois'),
    ('Indiana', 'Indiana'),
    ('Iowa', 'Iowa'),
    ('Kansas', 'Kansas'),
    ('Kentucky', 'Kentucky'),
    ('Louisiana', 'Louisiana'),
    ('Maine', 'Maine'),
    ('Maryland', 'Maryland'),
    ('Massachusetts', 'Massachusetts'),
    ('Michigan', 'Michigan'),
    ('Minnesota', 'Minnesota'),
    ('Mississippi', 'Mississippi'),
    ('Missouri', 'Missouri'),
    ('Montana', 'Montana'),
    ('Nebraska', 'Nebraska'),
    ('Nevada', 'Nevada'),
    ('New Hampshire', 'New Hampshire'),
    ('New Jersey', 'New Jersey'),
    ('New Mexico', 'New Mexico'),
    ('New York', 'New York'),
    ('North Carolina', 'North Carolina'),
    ('North Dakota', 'North Dakota'),
    ('Ohio', 'Ohio'),
    ('Oklahoma', 'Oklahoma'),
    ('Oregon', 'Oregon'),
    ('Pennsylvania', 'Pennsylvania'),
    ('Rhode Island', 'Rhode Island'),
    ('South Carolina', 'South Carolina'),
    ('South Dakota', 'South Dakota'),
    ('Tennessee', 'Tennessee'),
    ('Texas', 'Texas'),
    ('Utah', 'Utah'),
    ('Vermont', 'Vermont'),
    ('Virginia', 'Virginia'),
    ('Washington', 'Washington'),
    ('West Virginia', 'West Virginia'),
    ('Wisconsin', 'Wisconsin'),
    ('Wyoming', 'Wyoming')
)
